name: 'users'
description: 'base3 application'
app_version: '0.0.1'
host: 'localhost'
port: &port 9000

apptype: 'micro-service'

store:
  type: 'redis'
  host: 'localhost'
  port: '6379'

tortoise:
  connections:
    conn_users:
      engine: 'tortoise.backends.asyncpg'
      credentials:
        port: 5432
        host: 'localhost'
        user: 'telmekom'
        password: '123'
        database: 'b3tt_users'

  apps:
    users:
      models:
        - 'models.users'
      #        - 'aerich.models'
      default_connection: 'conn_users'

  use_tz: false
  timezone: 'UTC'

authorization:
  key: 'Authorization'

logging:
  version: 1
  request_logger: base
  formatters:
    brief:
      format: '%(asctime)s %(name)s %(levelname)s : %(message)s'
    detailed:
      format: 'time="%(asctime)s" logger="%(name)s" level="%(levelname)s" %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: WARNING
      formatter: brief
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: /tmp/base_app.log
      backupCount: 3
  loggers:
    base:
      level: DEBUG
      handlers:
        - console
        - file
      propagate: no
    tornado.access:
      level: DEBUG
      handlers:
        - file
    tornado.application:
      level: DEBUG
      handlers:
        - file
    tornado.general:
      level: DEBUG
      handlers:
        - file
  root:
    level: WARNING
    handlers:
      - console